### ISSUE TITLE
How to build the solution?(many build errors)

### ISSUE THREAD

**Issue by KulaGGin** [opentrack/opentrack#1045] opened 2020-02-07 12:46 UTC
I can't build the solution. There are multiple errors while trying to follow the [quick started guide](https://github.com/opentrack/opentrack/wiki/Developers'-Quick-Start-Guide-for-Windows).
First one is documented here: https://github.com/opentrack/opentrack/issues/1044

Second one, it says it needs CMake > 3.10 but when I try to build it with CMake 3.10, it throws this error:
![cmake-gui_LOGkfQUTNw](https://user-images.githubusercontent.com/16989713/74029846-4b095600-49b6-11ea-928c-0030099895b7.png)

And after I install last CMake 3.16.4, I get many errors in Visual Studio while trying to build the solution.
Here's video demonstration with all the errors:
https://youtu.be/Ov29Adg9Se4

Please note that I had to manually add `Qt5Gui_DIR`: `G:\Programs\Qt\5.12.0\mingw73_64\lib\cmake\Qt5Gui` in order for CMake to build, without it it was throwing the error I showed in #1044. So this could be the issue of build errors in Visual Studio, I don't know.

I would like to contribute, please don't ignore my issues @sthalik, I think they're pretty valid to create.

**Comment by sthalik** [comment] 2020-02-08 10:02
Duplicate of #1044.

**Closed by sthalik** 2020-02-08 10:02 UTC
