### ISSUE TITLE
opentrack crashing with pixel size set to 1.0 and low treshold

### ISSUE THREAD

**Issue by MathijsG** [opentrack/opentrack#282] opened 2015-12-23 13:12 UTC
When I have my settings like this all is good:

![image](https://cloud.githubusercontent.com/assets/529552/11977044/1aa5e0b8-a97f-11e5-8447-b219ed9934a7.png)

But when I reduce the min pixel size to 1.0 with the arrow application is crashing immediately.

**Comment by petsild** [comment] 2015-12-23 17:45
You've got enough absurd values of all parameters!
The PS3 Eye can handle at a resolution of 640x480 max 75Hz. The point size of the IR leds corresponding to the used lens, I have both variants of the PS3, so I carried out the comparison of the cameras.

- old the lens without the Ir filter 8 – 12 px
- new lens with the IR filter 3,50 – 4,20 px

Values are measured at the 70% treshold using the leds Harvatek HE3-290AC, at a distance of 60cm from the clip. If you've got a point size somewhere around 1px, the problem will be with the power of the dark filter in front of the lens, or inappropriate to the ir led on the clip.

**Comment by MathijsG** [comment] 2015-12-23 18:27
The FPS set to 120 is to easily test difference between 75 and 120 when I set resolution to 320 * 240.
I has no downside keeping this to 120, because it will serve the highest FPS it can get at selected resolution anyway.

I just used a single piece of floppy diskette and put it within the PS3 Webcam behind the lense. I don't necessarily have too few size of the pixels, but the problem is that sometimes Opentrack doesn't see the dots, while they are white enough to mee. It seems that increasing the threshold instead of lowering this, fixes this issue.

**Comment by sthalik** [comment] 2015-12-24 18:31
@petsild even if the parameters are absurd the software must not ever crash.

@MathijsG it's likely that there are too many points extracted. Compare this build https://db.tt/iwxRRNhV

**Comment by sniperwolfpk5** [comment] 2015-12-25 10:16
What are the prefered resolutions for ps3 eye 640x480 or  320 X 240 ?

**Comment by sthalik** [comment] 2015-12-25 10:27
You mean FPS? 75 for 640x480. Don't use 320x240 at all due to decreased precision.

**Comment by MathijsG** [comment] 2015-12-25 11:46
It depends on preference. Some prefer the higher speeds of 120 fps, but I
get indeed decreased precision and sometimes dots falling over each other.
Just play with it and try out what you like best.

Groeten,

Mathijs Groothuis
Op 25 dec. 2015 11:27 schreef "Stanisław Halik" <notifications@github.com>:

**Comment by sthalik** [comment] 2015-12-25 12:36
There's no preference to it. Speeds higher than 30 Hz are placebo. Shaking my head to make motion blur noticeable enough just makes my head and eyes hurt.

@MathijsG can you reproduce the crash in the test build?

**Comment by MathijsG** [comment] 2015-12-25 14:41
Would even lower it to 30 fps lower the amount of cpu being used? Will try
test build Sunday, celebrating Christmas now.
Op 25 dec. 2015 1:36 PM schreef "Stanisław Halik" <notifications@github.com

**Comment by sthalik** [comment] 2015-12-25 14:43
It would lower CPU usage, but in recent builds we're already as low as we can get while the software is minimized. The more significant bit is altered exposure with different framerates.

**Comment by MathijsG** [comment] 2015-12-26 23:28
Specific error didn't occur in test build here. Didn't try for hours, but no crashes with the treshold and pixel size combination. Well done again! :-)

**Comment by sthalik** [comment] 2015-12-28 04:58
Thanks! Marking as fixed.

**Closed by sthalik** 2015-12-28 04:58 UTC
