### ISSUE TITLE
Hybrid tracker feature request

### ISSUE THREAD

**Issue by amadeus1171** [opentrack/opentrack#488] opened 2016-11-03 17:25 UTC
Hi,

In 2.2 I was able to use two trackers.  I would use EDTracker for rotational tracking and the camera for positional tracking.  But in 2.3 that feature is no longer available.  Is it possible to reintroduce this feature into 2.3?

I'm just throwing this out there.  What about a hybrid tracker that can meld the inputs of two trackers together and present them as a single tracker.  Is that possible?

**Comment by sthalik** [comment] 2016-11-03 18:13
Duplicate of #171. It's gonna come but it's a bit of work and we have a big backlog.

**Closed by sthalik** 2016-11-03 18:13 UTC
