### ISSUE TITLE
development of the Wii tracker

### ISSUE THREAD

**Issue by cpuwolf** [opentrack/opentrack#718] opened 2018-01-08 23:32 UTC
hi sthalik,
could you consider abstract Camera class that has the ability direct output 2D points, such as WII remote?
if so, you can put point::extract as part  job of class Camera. then we can  add WII remote supporting here.

actually I have duplicated tracker-pt code to support WII remote, it works good. but duplicate is not a good idea. hope you can consider supporting WII remote
  

![2018-01-11_175518](https://user-images.githubusercontent.com/1320329/34819581-0e23453c-f6f9-11e7-895e-c1d62d3d921e.jpg)

**Comment by sthalik** [comment] 2018-01-10 07:35
What do you want to replace in `tracker/pt` in total? I can make it into a template class, just make a list.

**Comment by cpuwolf** [comment] 2018-01-10 22:56
hi Sthalik,
I would like to instance a special for example WIImoteCamera from Class Camera. then I can almost reuse whole tracker_pt procedure.  so please abstract Class Camera has the ability direct output 2D points.

**Comment by cpuwolf** [comment] 2018-01-11 05:48
hi Sthalik,
as I look at code at 2.9.3, 'Class Camera' is 'struct Camera' now.

**Comment by albertolg** [comment] 2018-01-11 08:01
@cpuwolf , how do you connect the wiimote? bluetooth? isn't there an adapter or a DIY interface to connect with the usb?

**Comment by sthalik** [comment] 2018-01-11 11:00
I'm abstracting `Camera` and `PointExtractor` then. :+1:!

**Comment by sthalik** [comment] 2018-01-11 18:04
@cpuwolf the API is in `pt-api.hpp` and you can see how to make a module in `module.cpp`.

**Comment by cpuwolf** [comment] 2018-01-11 22:56
@sthalik I never think you are so fast👍. Thank you ver much. let me learn it

**Comment by sthalik** [comment] 2018-01-12 09:25
@cpuwolf please contact me here or via email if you have any questions. Don't worry, I'm a friendly person :smile:

**Comment by cpuwolf** [comment] 2018-01-12 09:30
@sthalik I inhert WIICamera and WIIPointExtractor in below link.

https://github.com/cpuwolf/opentrack/commits/pt-reuse

but I found WIImote doesn't work baseing on cv::Mat& frame. 
this special camera WIICamera should direct output std::vector<vec2>& points,  which I cannot do it in WIICamera.

then look like I have to make WIICamera and WIIPointExtractor they communicate with each other. sounds strange.

**Comment by sthalik** [comment] 2018-01-12 10:03
@cpuwolf,

Currently `cv::Mat` is used unconditionally for image preview. But it makes sense, we shouldn't require PT to use OpenCV's internal format for all camera types. I'm making the change.

There's a class doing the preview, but you can either submit the preview yourself, or do nothing, in which case an empty image will be shown.

> BTW: my cmake+MSVC compile error with your latest baseline, they work OK on v2.3.9.

Please install Visual Studio 2017 Preview. Versions 2017 and 2015 are missing very important C++17 features.

**Comment by cpuwolf** [comment] 2018-01-13 04:04
@sthalik I plan to do migration by 2 steps. 
1. migrate WIImote point tracker from 2.3.1_fix2 to 2.3.9.
2. adapt to latest baseline

but on step 1, I am stuck now. I am confused about pointtracker:POSIT input parameter-points.
per my understanding the input points coordinate, x(-0.5~0.5) ,y(-0.5~0.5). this is so-called screen coordinate as you mentioned at

https://github.com/opentrack/opentrack/commit/537a88e522314753149e1ea7921489e58043b40c

but it does't work on v2.3.9, but i does work on v2.3.1_fix2. again I am comparing POSIT() code between v2.3.1_fix2 and 2.3.9. seems no big change.

if you could help "Ding" me, please comment. thank you. I will continue studying and searching

**Comment by sthalik** [comment] 2018-01-13 04:40
@cpuwolf,

The `Y` equation in `vec2 dt` should be `-(dot.RawY - 768.f/2.f)/1024.f`

These are correct screen coordinates, providing `RawX` and `RawY` are on the `0->1024` and `0->768` intervals. The values for POSIT (screen coordinates) are meant to be on the `(-.5)->+.5` interval. Because the Y image plane has a lower aspect ratio, it can only reach up to 0.375.

For focal length you can borrow the formula computing it from the FOV. Or just return `1`.

I wish we could use templates and get rid of this inheritance API, but Qt doesn't allow for template classes at all.

**Comment by cpuwolf** [comment] 2018-01-13 12:48
@sthalik I don't know how should I thank you. you save time lots of debug time. you don't have donation ha.

![zbmate_com_obs_addon02 2018-01-13](https://user-images.githubusercontent.com/1320329/34906180-9633bcc2-f8a2-11e7-8be3-e5f53eaf79e2.jpg)

it works now. actually creen coordinate is equal. the root cause is focal length. as you said "return 1" is the "Ding" on my brain. Thank you so much.:+1:. :+1:.

then I can move on to the next step. cheers

**Comment by cpuwolf** [comment] 2018-01-13 23:45
@sthalik I dont know whether I should borther you. I tried vs2017 community preview. compile errors are same
`
“<function-style-cast>”: 无法从“initializer list”转换为“QLatin1String”
`

**Comment by sthalik** [comment] 2018-01-13 23:58
What Qt version are you using? Do you get other errors outside from `QLatin1String`?

Don't worry just ask the questions.

**Comment by sthalik** [comment] 2018-01-14 00:00
I just remembered at the fridge. In `cmake-gui` add `-std:c++17` as another argument to `CMAKE_CXX_FLAGS`.

**Comment by sthalik** [comment] 2018-01-14 00:12
@cpuwolf 

Find the installation location for the preview. It's always in the `Preview` subdirectory. For me it's `C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional`.

This for me but you can easily adapt:

`C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\VC\Auxiliary\Build\vcvarsall.bat`

Open `cmd.exe`, then drag `vcvarsall.bat` to the window. It'll copy the file's full path into the console window. Then add parameters, like this:

> C:\Users\Administrator>"C:\Long\Path\To\vcvarsall.bat" x86

Launch `cmake-gui` from it. Create a new build directory for opentrack and point to the sources. **Use NMake Makefiles** as the generator!

Optionally you can select `opentrack/cmake/msvc.cmake` when CMake asks for a "toolchain file" when generating the build directory for the first time. It sets aggressive optimizations.

While still in the console window, go into the build directory and type `nmake`. It should start building.

Please contact me if you have any problems or need additional information.

**Comment by sthalik** [comment] 2018-01-14 00:21
As long as you're able to get `vcvarsall.bat` work, you can type `cl` and paste me the version number on the first line. Thanks.

**Comment by sthalik** [comment] 2018-01-14 00:47
It should work. opentrack forces `std:c++latest`. I recommend Qt 5.10 or 5.9.x at least.

**Comment by cpuwolf** [comment] 2018-01-14 01:15
@sthalik I used Use NMake Makefiles as generator, then I got exactly same error in console

`
f:\works\github\opentrack\compat\string-literal-operator.hpp(8): error C2440: “
<function-style-cast>”: 无法从“initializer list”转换为“QLatin1String”
`

I guess one possibility is you are using professional version, I am using community version?

**Comment by sthalik** [comment] 2018-01-14 01:25
No, it's not a problem. Can you please switch to English (for example on a different user, or a VM) and show me the compiler output?

**Comment by cpuwolf** [comment] 2018-01-14 01:45
@sthalik hahah. good news! not VS. not preview. it is caused by Qt5.7, after I updated to Qt 5.10. compile passed

**Comment by cpuwolf** [comment] 2018-01-16 08:02
@sthalik I roughly have done the integration. then I cannot test it

one question about module.cpp. should I duplicate one? then how user select different modules? I don't see any UI change

**Comment by cpuwolf** [comment] 2018-01-16 08:35
@sthalik below logic seems not quite correct. why not close camera firstly, then wait thread? because close signal has not chance to send out because thread is blocked by wait()
`
Tracker_PT::~Tracker_PT()
{
    requestInterruption();
    wait();

    QMutexLocker l(&camera_mtx);
    camera->stop();
}
`

**Comment by sthalik** [comment] 2018-01-16 10:50
@cpuwolf  camera is still in use while the `run()` loop runs. It's not meant to be stopped unless `run()` exits.

1. Don't, it's done by the aforementioned `run()` method.
2. Why do you need it? Can't you put in the `stop()` method?

**Comment by cpuwolf** [comment] 2018-01-16 12:17
@sthalik I have block function inside camera

**Comment by sthalik** [comment] 2018-01-17 00:18
@cpuwolf you can wait for it to unblock in `pt_camera` destructor.

**Comment by cpuwolf** [comment] 2018-01-17 03:19
@sthalik non-block re-construction has been done. 

then how user can dynamically select different modules?

**Comment by sthalik** [comment] 2018-01-17 10:51
@cpuwolf link to `opentrack-tracker-pt` in the `CMakeLists.txt` file, initialize `Tracker_PT` in your tracker like in `tracker-pt/module.cpp` subclassing of `pt_runtime_traits`.

**Comment by cpuwolf** [comment] 2018-01-18 01:57
OMG. my understanding was wrong. thank you for your clarification. will integrate and rebase and test, then pull request

**Comment by cpuwolf** [comment] 2018-01-18 02:27
@sthalik I got below link error, seems that one .dll cannot include 2 modules
```
>wii_module.cpp
1>wii_module.obj : error LNK2005: _GetConstructor already defined in module.obj
1>wii_module.obj : error LNK2005: _GetDialog already defined in module.obj
1>wii_module.obj : error LNK2005: _GetMetadata already defined in module.obj
```

**Comment by sthalik** [comment] 2018-01-18 08:42
You can now. Link against `opentrack-tracker-pt-base`. 🐱

**Comment by cpuwolf** [comment] 2018-01-18 13:46
@sthalik OK. common code generates 2 dlls. but see below error
```
1>   Creating library F:/works/GitHub/output/opentrack/tracker-pt/Release/opentrack-tracker-pt.lib and object F:/works/GitHub/output/opentrack/tracker-pt/Release/opentrack-tracker-pt.exp
1>wii_camera.obj : error LNK2019: unresolved external symbol "public: __thiscall wiimote::wiimote(void)" (??0wiimote@@QAE@XZ) referenced in function "public: virtual enum pt_camera_open_status __thiscall pt_module::WIICamera::start(int,int,int,int)" (?start@WIICamera@pt_module@@UAE?AW4pt_camera_open_status@@HHHH@Z)
1>wii_camera.obj : error LNK2019: unresolved external symbol "public: bool __thiscall wiimote::Connect(unsigned int,bool)" (?Connect@wiimote@@QAE_NI_N@Z) referenced in function "private: enum pt_module::wii_camera_status __thiscall pt_module::WIICamera::_get_frame(class cv::Mat &)" (?_get_frame@WIICamera@pt_module@@AAE?AW4wii_camera_status@2@AAVMat@cv@@@Z)
```
if I put my code in same folder, opentrack-tracker-pt will compile with my code, that is unneccessary. so should we re-org the directory structure?
1. base(common code)---static lib
2. pt(folder )opentrack-tracker-pt---.dll
3. wii(folder )opentrack-tracker-wii-pt---.dll
creates 3 folders to avoid unneccessary comple&link

**Comment by sthalik** [comment] 2018-01-18 18:41
Hey,

1. Update to the latest opentrack revision
2. Put your own code in `tracker-wii/` with a short `CMakeLists.txt`. See below for a possible example.
2. Don't create a static library. Link against the static `opentrack-tracker-pt-base` in the latest revision.

Example `CMakeLists.txt`:

```
find_package(OpenCV 3.0 QUIET)
if(OpenCV_FOUND)
  otr_module(tracker-wii)
  target_link_libraries(opentrack-tracker-wii opentrack-tracker-pt-base)
endif()
```

This should work

**Comment by cpuwolf** [comment] 2018-01-18 23:08
@sthalik 🐱  will follow up. Thanks

**Comment by cpuwolf** [comment] 2018-01-19 02:49
@sthalik this time the whole structure is clear, rebase is done.🐱

 sorry but new problem comes up. have you noticed that your tracker-pt has lost its resources?
![2018-01-19_104844](https://user-images.githubusercontent.com/1320329/35132447-5ce8aabe-fd06-11e7-942f-57583c990e79.jpg)

**Comment by sthalik** [comment] 2018-01-19 13:19
Yesterday I changed it a bit because the default camera implementation was in `pt-base` by accident. Now it's in the separate module.

Can you create your own dialog, removing things you don't need? If it's a problem don't do it! We could move the original dialog to the `pt` module and have cleaner `pt-base`. But don't waste time if you're ok with the existing dialog.

**Comment by sthalik** [comment] 2018-01-19 13:20
If you `git pull` then the resources are back.

**Comment by sthalik** [comment] 2018-01-19 13:34
Good catch! I was about to release a version with broken images :)

**Comment by cpuwolf** [comment] 2018-01-19 22:31
@sthalik I  would love to reuse UI. the only thing may can improve on UI is "Device", this may confus users. if "Device" can show "WIImote IR camera", that will be better
![zbmate_com_obs_addon01 2018-01-20](https://user-images.githubusercontent.com/1320329/35174739-68b0be86-fdab-11e7-91e8-609b852a2fd6.jpg)

**Comment by sthalik** [comment] 2018-01-20 10:36
@cpuwolf amazing work in time for the 2.4.0 release!!! ❤️ 

Which other options from the PT menu you want removed or changed? Camera settings button comes to mind.

**Comment by sthalik** [comment] 2018-01-20 10:38
You also say the FOV is 42 degrees. You also only need the fov in case of establishing the focal length. I recommend you reuse our focal length code, do you want to?

**Comment by cpuwolf** [comment] 2018-01-20 11:16
@sthalik happy hours coorperating with you:heart: cheers!!

Oh. exactly. 
1.  Camera settings is useless for WII
2.  I did some study, FOV of WII is about 42 degrees

but these items is not quite urgent, we can optimize them step by step

**Comment by cpuwolf** [comment] 2018-01-21 00:32
@sthalik 
```
struct OTR_PT_EXPORT pt_camera_info final
```

pt_camera_info is final class, I cannot reuse it

**Comment by sthalik** [comment] 2018-01-21 07:40
A short partial review. Please note the following:

```
	m_pDev = new wiimote;
	if (m_pDev == NULL)
	{
		stop();
		return cam_open_error;
	}
```

`m_pDev` never returns NULL. It's always a pointer to something. That block will never execute. If you can check whether it works change the check expression, or just assume it worked.

I ***heavily*** recommend using

```
#include <memory>

std::unique_ptr<wiimote> m_pDev;
```

Then you can force-destruct using `m_pDev = nullptr;` and create using `m_pDev = std::make_unique<wiimote>("optional-argument", "some-other-optional-argument", ........);`.

This has advantages

- the pointer will not leak when destructing the class
- setting to `nullptr` won't crash if it's NULL already
- setting to new value will free behave as set to `nullptr` first, i.e. won't leak

For focal length computation, in

```
pt_camera_open_status WIICamera::start(int idx, int fps, int res_x, int res_y)
```

Do this:

```
cam_info.fov = 42;
cam_desired.fov = 42;
```

You can set other parameters and they're gonna show as frame size and FPS in the dialog. I'm going to explain how you can reuse the dialog in another post.

The WiiYourself library has a very bad, incorrect license. Written with good intentions but bad as a legal document (which it is). I'm adding the license terms to the `3rdparty-notices/` directory for now. We're going to have the phrase the license requires, added to the `tracker-wii` options so we fully abide by the license terms (as we do with other software we depend on).

Please change the copyright so it points only to you in `tracker-wii`. There's no significant code by others so you're the only author. You can remove me and Patrick since nothing really comes from us.

**Comment by sthalik** [comment] 2018-01-21 08:42
Also @cpuwolf please add the license terms where you added your copyright. It's that "Permission to use..." thing. By default copyright gives no rights to anyone but the author.

**Comment by cpuwolf** [comment] 2018-01-21 12:27
@sthalik How should I thank you for the big reply, I learnt a lot. actually I am not good at cplusplus. thanks for your patient.

https://github.com/opentrack/opentrack/pull/729

# focal length
OK. will update once you are ready

# drawing
I think

![zbmate_com_obs_addon02 2018-01-21](https://user-images.githubusercontent.com/1320329/35194152-6efa1c6c-fee9-11e7-935f-8a4da3a86b40.jpg)

**Comment by sthalik** [comment] 2018-01-25 15:22
@cpuwolf,

#### Focal length

It should be enough to set `fov` to `42` when returning `pt_camera_info`. The code should return a different Z value. Then, remove the calibration value and measure the real distance to the "main" dot that's now the yellow cross. They distances should match in centimeters, as long as the model's values are in millimeters.

Depending on whether the displayed distance and your measurement match, we'd have to decide what to do next.

#### User interface

You can remove individual items from the settings. Open the `.ui` file in PT and look up their names. If they have a generic name like "combobox" or "label", assign proper names and then access them like `ui.something->hide()`. Send the changes to PT's `.ui` file along with the rest.

I've made the change so you can subclass `TrackerDialog_PT` and do changes in resulting class' constructor. I recommend you hide the entire camera settings groupbox since these things don't work for the Wiimote tracker at all.

Don't subclass Qt classes separately when subclassing `TrackerDialog_PT`. It already subclasses `QDialog`, and thus `QWidget`, and `QObject`. Subclassing Qt stuff in a "diamond inheritance" pattern will break the dialog and probably won't compile at all.

#### WiiYourself library

I CC'd you when messaging the library's author. He responded rudely, but also proposed changing his license if someone maintained his original library. We could take it on as an opentrack project, say, `opentrack/wiiyourself`. What do you think?

**Comment by sthalik** [comment] 2018-01-25 15:23
You can also try setting the FOV in the dialog to `42` and see if the distances are real.

**Comment by cpuwolf** [comment] 2018-01-26 03:42
# focal length
now problem is `pt_camera_info::get_focal_length()` is compiled in `libopentrack-tracker-pt-base.lib`
, then while wii has to link with this base lib  `libopentrack-tracker-pt-base.lib`, function `get_focal_length()` is duplicated defined if I redefine this function

# UI
OK. subclassing TrackerDialog_PT

**Comment by sthalik** [comment] 2018-01-26 05:28
1. I was wrong, you don't need to use it directly. Internal PT code uses it.
2. It's `public static` so it's meant to be called directly.

I'm forwarding the guy's rude reply. He wants to change the license for his own code if someone takes care of it.

We COULD move wiiyourself into a separate repo and include it in `tracker-wii` as a submodule. But the question is, do we want even to? It's work and responsibility to maintain it over time. Also I can't test it personally due to lack of a Wiimote.

**Comment by cpuwolf** [comment] 2018-01-26 06:03
haha. I see it. it is really rude.

https://github.com/opentrack/opentrack/pull/735

check my first-step pull request please.

so we have to be maintainer of wiiyourself. I can take it because I have Wiimote in hand.

**Comment by sthalik** [comment] 2018-01-26 06:07
@cpuwolf I'd also like to make some quality changes. Can you work with me on that?

I'd like to grant you developer access. Do you accept? There are only few basic rules. Please send me an email.

**Comment by cpuwolf** [comment] 2018-01-26 06:12
@sthalik yes, I accept. thank you very much. kernel.org has my name, so I know how to cooperate. only think I worry is I am not good at cplusplus, because I am assembly-code guy. 😄

**Comment by sthalik** [comment] 2018-01-26 06:37
@cpuwolf When I started back on facetracknoir I didn't know any C++ at all. After the fork, until C++11 came out, opentrack had real messy code because C++ wasn't any good as a language.

There are few good features in C++ you'll appreciate:

- RAII saves from having to write data-freeing epilogues or labels on each return path, including error paths. It's used the same way for using scoped mutexes.
- The template system is algebraic, and most importantly it can compute like a real programming language, except fully at compile time. People use it to great success in libraries like Eigen.

You'll see that opentrack doesn't use OOP "just because" like some dogma, it's closer to being written in a multiparadigm language. 

- - -

Here are some ideas that may give you the feel of the project. There aren't really any codified "rules". Common sense on how to behave with people is enough to proceed.

- We're using the best solutions there are, no matter who comes up with them. If some piece of code I wrote is bad, you can just say so and discuss it.
- Discuss refactorings of the core code. We don't wanna have conflicting versions. Overall it's better to discuss more rather than less.
- As long as you maintain the tracker and no one else messes with it, but you can mess with "unowned" code. It's only OK for others to change the code you maintain if it fails to compile or work due to some core code change. These changes are normally very minor.
- You **do not** have to be professional like some kind of corporate representative, we're all volunteers here, and users understand this. It's your choice. Just don't be rude toward the users. Act like a normal person does in a group and it's enough.
- opentrack **never** accepts GNU GPL-licensed code. As for GNU Lesser GPL, see `CONTRIBUTING.md`.

Some more ideas.

 - It's OK for internal discussions to take place here, in public. It's better for disagreements to be public, for the sake of transparency. But it's fine to discuss over email all the same.
- The "unstable" branch is marked as protected on Github and doesn't accept rewriting history. It can only be disabled for a split second in case of some fuckup.
- If you know how to use git, try to avoid merge commits and rebase "oops" commits. If you don't know how to rebase, just make merge commits and "oops" commits anyway.

You're being sent an invite to the project.

**Comment by sthalik** [comment] 2018-01-26 07:06
Please note, only (5) is a "hard" rule, because it's the law.

But here's another thing to note (the numbering is a poor joke).

101. Don't expect users to know English perfectly. Don't close issues because of this. I'll personally handle it if it's a problem.

Personally I tend to change my vocabulary and grammar when dealing with people with visibly poor understanding of English. Sometimes making grammar errors on purpose so that the sentence structure is more simple. It's not judgemental, just certain people weren't taught or self-taught English as much.

**Comment by cpuwolf** [comment] 2018-01-26 07:15
some summary in my mind:
1. no GPL, as far as I know GPL some version is like a worm.
2. be nice
3. git I am good at it.

**Comment by sthalik** [comment] 2018-01-26 07:30
Welcome aboard.

**Comment by cpuwolf** [comment] 2018-01-26 08:07
🍺 🍺 

❔  `void set_fov(double value)`  is a setting function, return? 😃

**Comment by sthalik** [comment] 2018-01-26 08:14
Just do nothing in `pt_camera::set_fov()`. When you must return `pt_camera_info` in `pt_camera`, set the `fov` element to `42`. Set `res_x` and `res_y` to real values, i.e. `1024` and `768`. Set `fps` to what you see fit. You can set `idx` to `0` to be safe but it's presently not checked by the code.

**Comment by sthalik** [comment] 2018-01-26 09:03
Can you move `tracker-wii` to the main directory?

**Comment by albertolg** [comment] 2018-01-27 13:34
I have just downloaded latest test build... what I need to setup for opentrack to use the wiimote? thanks

p.s.
the wiimote is paired, opentrack see an horizontal line moving but the points are not visibles

**Comment by cpuwolf** [comment] 2018-01-28 05:12
@albertolg 
1. get the wiimote paried
2. see horizontal line moving in opentrack
3. your 2 LEDs point must in front of IRcamera of WIIMote
4. in settings, select your model: clip or cap, and enter our LEDs custom data

**Comment by cpuwolf** [comment] 2018-01-28 10:11
@albertolg below is my setup
![](https://github.com/cpuwolf/tracker-wii-pt/raw/v2.3.9/doc/wiimote_how.jpg)

if you see horizon is moving, which means your BT dangle is working. here I highly doubt whether your IR camera on front of WIImote is working?

another posiblity is it is IR camera, you should IR leds, not normal LEDs.  I didnt tried IR led, because I use IR led. plz try another leds

**Comment by albertolg** [comment] 2018-01-28 10:34
the leds I use are IR and I use it without any issue with the PS3eyecam. I tested the wiimote with a standard TV remote and it see the flashing led, and if I put my leds very close to the wiimote then it see it. Probably your leds are brighter than mine. Is possible to add a slider to change the wiimote sensibility to make it more sensible?

**Comment by cpuwolf** [comment] 2018-01-28 11:02
by default, it is highest sensitivity of IR camera

**Comment by cpuwolf** [comment] 2018-01-28 11:40
can you try this full sensitivity setting?
[libopentrack-tracker-wii_full_sens.zip](https://github.com/opentrack/opentrack/files/1671031/libopentrack-tracker-wii_full_sens.zip)

as I tested, it introduce more unwanted light. if this one still doesn't work for you. then we should not take too much afford on that. because there is no open public doc descripe how to set steps of sensitivity. only I can find is full sensetivity

**Comment by albertolg** [comment] 2018-01-28 12:07
now I can see them but at a very close range.... reading about the led's wavelength, well, I think I need to buy the 940 because the leds I'm using now are 760~800nm

**Comment by cpuwolf** [comment] 2018-01-28 12:22
I highly recommend you LED SFH485p as show above, which 40 degree view angle, and more importance is it is proved working LED with WIImote.

each camera has its own characteristics, I mean ps3eye and WIIcam they are not comparable

**Comment by albertolg** [comment] 2018-01-28 12:40
yeah.. I had the SFH485p some years ago when I used freetrack.. now I can't find them and I need to buy again

**Comment by sthalik** [comment] 2018-01-29 17:27
@albertolg 
> now I can see them but at a very close range.... reading about the led's wavelength, well, I think I need to buy the 940 because the leds I'm using now are 760~800nm

Maybe they're not powerful enough. How large are they on PS3 Eye on low FOV setting? Mine are 10-13 pixels depending on gain settings. Got 3 clips like this. All are ~850 nm.  Some people use LEDs showing as ~2px in opentrack and that's no good.

Damn I need to find out how to make resistor configurations. So many years with a paper clip... :)

**Comment by sthalik** [comment] 2018-01-29 17:29
@cpuwolf how much filtering do you need with Accela? Try rotation-deadzone=0.05, and then check rotation sensitivity. Mine is ~0.45 sensitivity, though your setup is technically superior anyway.

**Comment by sthalik** [comment] 2018-01-29 17:29
Also can you confirm the newest prerelease works ok?

**Comment by albertolg** [comment] 2018-01-29 20:07
@sthalik I have the wrong resistors in my setup, added some resistors in parallel because I don't have the right value and now the leds are brighter, they where around 6-7 now are 11-12, tomorrow I need to find some resistors to have about 70-80ohm, now are about 120ohm. I use this to make my calculations http://led.linear1.org/led.wiz

**Comment by cpuwolf** [comment] 2018-01-29 23:19
prerelease? @sthalik where I can find it? any link I can test?
if you mean latest code, for sure, I tested with every change. all works good

**Comment by sthalik** [comment] 2018-01-31 08:22
@cpuwolf http://opentrack.misaki.pl always redirects to prerelease storage.

@cpuwolf does the tracker see a lighter or a match burning? The PS3 Eye sees it as very bright, brighter and larger than 850 nm LEDs. Here are wavelengths borrowed from Wikipedia:

![image](https://user-images.githubusercontent.com/1896811/35612217-3d4bf97a-0668-11e8-94f9-7b9bb5347a00.png)

**Comment by sthalik** [comment] 2018-01-31 12:55
@cpuwolf,

I took the liberty of moving the `wiiyourself` directory into `tracker-wii/`.

Also I recoomend installing the English language pack if only to get fonts :)

**Comment by cpuwolf** [comment] 2018-01-31 14:09
@sthalik a lighter as I tested is invisible. so that is another benefit of WIImote.

no problem at all, I will follow up after your commit.

**Comment by albertolg** [comment] 2018-02-02 06:30
I have ordered a new BT dongle, the one I have now is recognized randomly by W10, and every time I have to rebind the controller, then also the new IR leds and I will do some tests. @cpuwolf , what is your CPU use with the wiimote? thanks

**Comment by cpuwolf** [comment] 2018-02-03 14:02
exactly, every time you reboot your PC, you have to rebind the WIImote. CPU usage is around 2~10%

**Comment by sthalik** [comment] 2018-02-04 15:37
What do you mean by "rebind"? Does it pertain to the Device Manager?

**Comment by cpuwolf** [comment] 2018-02-04 23:35
@albertolg @sthalik my understanding is no fault in dongle. I think it is caused wiimote, which is not designed to connect Windows. "rebind" means 're-pair BT device"

**Comment by sthalik** [comment] 2018-02-05 01:05
@cpuwolf can this be automated?

**Comment by sthalik** [comment] 2018-02-05 08:37
@cpuwolf, I've made a few commits in order to fix minor problems with the build. I'm uncomfortable making changes on your turf. Please indicate whether you're displeased by it.

Here are reasons for the changes:

- 33e9c9aa56a13ee95bbe26f71692aa5288bcc6b8, 8dfcc01968df0795dbf8cf83e4908c375b3789af -- it now matches the source-code layout in opentrack
- 906b50a33bdd98ef42def15807dcda4d82c27909, 0d82a0ccc3c9bb49f28f18e7460a5366e06516bc -- fix -W4 warnings on build. Happens because release builds use my `msvc.cmake` toolchain file that includes -W4.
- 574ce54af4d17af1903f3e221b7b51803978b5da -- the Linux (and unmaintained OSX) platforms are second-class citizens but they must build cleanly.

**Comment by cpuwolf** [comment] 2018-02-05 23:18
@sthalik obviously you have deeper understanding about opentrack. Thank you for considering all factors into these changes.

**Comment by albertolg** [comment] 2018-02-06 08:56
If I'm not wrong Dolphin have the auto-pair
https://github.com/dolphin-emu/dolphin

**Comment by cpuwolf** [comment] 2018-02-06 11:47
@albertolg @sthalik great news! auto pair with windows BT stack is done. hahaha :laughing: :rocket:

**Comment by MathijsG** [comment] 2018-02-06 12:51
@sthalik would it come in handy for you if you'd have a Wii Mote? I can order you one and send it to your address. Please let me know.

**Comment by sthalik** [comment] 2018-02-08 10:05
@albertolg we can't use Dolphin as it's under GNU GPL 2.

@MathijsG thank you, but no. @cpuwolf is great at maintaining it himself. 👍

**Comment by cpuwolf** [comment] 2018-02-08 10:31
to whom concerning about WIImote,

see our new friendly UI, which will tell you what to do next in preview window

![screenhunter_04 feb 08 18 29](https://user-images.githubusercontent.com/1320329/35968193-207a63e4-0cfe-11e8-914c-62fa8481a71d.jpg)

**Comment by albertolg** [comment] 2018-02-08 12:29
@cpuwolf , you can also press the button 1 & 2 without opening the battery box, try it

**Comment by cpuwolf** [comment] 2018-02-08 22:55
@albertolg I know that
1. button 1&2 is for one-time bt pair
2. sync is for permanent pair

my expectation is keep you a permanent link

**Comment by cpuwolf** [comment] 2018-02-21 04:51
crash fix
https://github.com/opentrack/opentrack/commit/9df0a0cf266cf1afac8170ca36aadbf2e5014191

**Comment by sthalik** [comment] 2018-03-03 07:08
@cpuwolf maybe you want to put this in `wii_dialog_pt::wii_dialog_pt()`?

```
ui.tabWidget->removeTab(0);
```

**Comment by cpuwolf** [comment] 2018-03-05 06:23
@sthalik tab0 status area I still want to keep, which see tracking status.

**Comment by sthalik** [comment] 2018-03-07 01:55
@cpuwolf the "Status" groupbox is visible on all tabs, as it's outside the tab widget proper. But of course I leave you free hand over the tracker's dialog.

**Comment by sthalik** [comment] 2018-03-15 04:33
@cpuwolf tell me if you have any problems with the `.sln` build. GNU Make was broken and I think I found a solution for both of the build systems, and Ninja as well. It affects the i18n build.

**Comment by cpuwolf** [comment] 2018-03-18 00:05
@sthalik sorry for late
https://github.com/opentrack/opentrack/tree/89779de6b084a54711cf360d7fa145f433795623
it works fine with MSVC

**Comment by sthalik** [comment] 2018-05-30 05:40
@cpuwolf can you build with Visual Studio right now? I've had to make changes to the dependency chain again 😢 I can confirm it works with GNU Make and Ninja.

**Comment by cpuwolf** [comment] 2018-06-08 03:37
@sthalik just did a quick test on below commit

https://github.com/opentrack/opentrack/commit/633ae657aea8748c2f76ab111837d967d7dc9d08

I can confirm CMake 3.10.1+ MSVC 2017 preview works great

**Closed** 2019-04-24 07:55 UTC
Labels: discussion, feature

**Comment by TalalMash** [comment] 2020-11-26 01:09
Hello, any idea if libopentrack-tracker-wii_full_sens_3.zip is implemented in the latest version? The current version is too weak, while old FreeTrack has the IR visible with no issues, thanks @cpuwolf !

**Comment by TalalMash** [comment] 2020-11-26 23:36
[opentrackwiisensfi-githubformat.zip](https://github.com/opentrack/opentrack/files/5605313/opentrackwiisensfi-githubformat.zip)
Latest working opentrack 3.11 working wii mote support with max sensitivity, works with any led now. I simply changed the registers. From WiiBrew:
![image](https://user-images.githubusercontent.com/67645271/100397135-de4c6e80-3050-11eb-923f-df291d7b3a9a.png)
