### ISSUE TITLE
Feature request: ability to change mapping within profile or changing profiles with keybind

### ISSUE THREAD

**Issue by unhappytroll** [opentrack/opentrack#636] opened 2017-06-16 21:07 UTC
Reason: playing in Arma 2/3 there is a need for 2 different mappings. One with small/none deadzone for flying helicopters/planes, and one with big deadzone for infantry. right now switch between two profiles requires alttabbing, which is not desirable.
So the ideal would be switching mappings (or force larger deadzone) inside a profile, but switching profile would be enough too.

**Comment by sthalik** [comment] 2017-06-18 07:09
It's already accepted. Closing as duplicate of #609.

**Closed by sthalik** 2017-06-18 07:09 UTC
