### ISSUE TITLE
Can't find neuralnet

### ISSUE THREAD

**Issue by MrNoob025** [opentrack/opentrack#1914] opened 2024-08-11 16:54 UTC
Hey guys, I was trying to find NeuralNet since i heard that it's good, I installed multiple OpenTrack versions but still can't seem to find it.

Can anyone help?
![Screenshot (86)](https://github.com/user-attachments/assets/4f0378bc-fd04-4f3b-ba95-37f40091dc50)

**Comment by kakra** [comment] 2024-08-11 20:58
Probably duplicate of #1908 - did you install the 64 bit version?

**Comment by DaWelter** [comment] 2024-08-12 06:40
I wonder, do you happen to have a really old CPU?

**Comment by sthalik** [comment] 2024-08-12 11:06
Did you install the Visual C++ redistributable by any chance?

**Comment by MrNoob025** [comment] 2024-08-12 11:11
Well I don't remember installing it, but I have this folder on my pc, it's empty though.

**Closed** 2024-08-12 11:15 UTC
