### ISSUE TITLE
OpenTrack freeze when click start button

### ISSUE THREAD

**Issue by FlyMakerBR** [opentrack/opentrack#450] opened 2016-09-09 16:29 UTC
OpenTrack rc99p11 is freezing randonly after pres start.

Input: Aruco
Output: freetrack 2.0 Enhanced
Filter Accela

Some days work others dont!

Opentrack is not responding and just that for hours

**Comment by FlyMakerBR** [comment] 2016-09-09 16:39
Freezing now when click input properties too

**Comment by sthalik** [comment] 2016-09-09 17:34
First try https://github.com/opentrack/opentrack/wiki/experimental-builds to see if it's gone.

If it's not gone in the latest build I'm gonna provide some debug instructions.

**Comment by sthalik** [comment] 2016-09-09 17:35
Also state your CPU model (no other hardware details needed).

**Comment by FlyMakerBR** [comment] 2016-09-09 17:35
FX8350 4.0 Ghz

**Comment by sthalik** [comment] 2016-09-09 17:42
Then check the latest build. Backup your config first, after tests replace with the backup. This is because mapping format changed and you'll start with no mappings in the new config. BUT rc12 will migrate your old mappings. BUT if you keep the config from the experimental build it's not gonna migrate.

**Comment by FlyMakerBR** [comment] 2016-09-09 17:43
Thx.

I started with Default preset and worked.

**Comment by sthalik** [comment] 2016-09-09 17:44
@FlyMakerBR can I assume it's fixed, then?

rc12 will come later today.

**Comment by FlyMakerBR** [comment] 2016-09-09 17:45
Freeze again. I hit start -> Stop -> Start -> freeze

**Comment by sthalik** [comment] 2016-09-09 17:48
What's your webcam? Can you replug it? Also wait about 5 seconds since some buggy webcam drivers crash on quick stop/start.

**Comment by FlyMakerBR** [comment] 2016-09-09 17:49
Microsoft HD5000

I will try replug again

**Comment by FlyMakerBR** [comment] 2016-09-09 17:51
The default.ini is missing some info. Show only that:


[modules]
tracker-dll=aruco -- paper marker tracker

[aruco-tracker]
camera-name=Microsoft\xae LifeCam HD-5000

**Comment by FlyMakerBR** [comment] 2016-09-09 17:53
I used Opentrack yesterday without problem. Some random freezes on start but after a minute worked.
Today i have tried for hours

**Comment by FlyMakerBR** [comment] 2016-09-09 18:02
I tried to use virtual cam too.
ManyCam
IpCamera
VirtualCamera

Not effective

**Comment by FlyMakerBR** [comment] 2016-09-09 18:06
All experimental builds not worked.
Deleted default.ini before all tests

**Comment by FlyMakerBR** [comment] 2016-09-09 18:40
I tried all trackers. Only when webcam is needed the program freeze

**Comment by sthalik** [comment] 2016-09-09 18:43
Why would manycam not work?

**Comment by FlyMakerBR** [comment] 2016-09-09 18:46
Just not work.
I select manycam in devices. Hit start and freeze

**Comment by FlyMakerBR** [comment] 2016-09-09 18:48
Tried static image on manycam and always freeze. But show the image on opentrack before freeze.

**Comment by sthalik** [comment] 2016-09-09 18:50
Did you get any windows updates today or yesterday?

Did you install or update codecs?

**Comment by FlyMakerBR** [comment] 2016-09-09 18:53
No changes. Only if have background updates.

But i do not see any update screen even on restart.

**Comment by sthalik** [comment] 2016-09-09 18:59
There's update history in the control panel.

**Comment by FlyMakerBR** [comment] 2016-09-09 18:59
I made a new instalation with setup.exe and now i can start. No freeze

All portable releases not working for me.

I'ts weird. I move to portable versions because problems with setup releases. Now i have to go back to binarized release.

**Comment by sthalik** [comment] 2016-09-09 19:00
It's probably a permission issue. Make sure to assign yourself ownership and full control over all the directories and files inside the portable install directory.

**Comment by sthalik** [comment] 2016-09-09 19:00
What's the problem with the installer? Report it next time rather than working around.

**Comment by FlyMakerBR** [comment] 2016-09-09 19:03
"Make sure to assign yourself ownership and full control"

I made that with all releases.
The problem is not the installer. Opentrack instalation stoped so i move to portable. Now portable stoped i move to new instalation

**Comment by FlyMakerBR** [comment] 2016-09-09 19:21
Now i'm trying to disable outputs but the settings always return to default.
I running with ADM privileges. Something is wrong.

**Comment by FlyMakerBR** [comment] 2016-09-09 19:22
Same with invert option. Always return to disable.

**Comment by sthalik** [comment] 2016-09-09 20:38
These ones are broken in rc11. Fixed in experimental.

**Comment by FlyMakerBR** [comment] 2016-09-11 22:13
Every time i restart computer need to reinstall OpenTrack

**Comment by sthalik** [comment] 2016-09-16 16:26
@FlyMakerBR I had it reproduced. See https://github.com/opentrack/opentrack/issues/454

**Comment by FlyMakerBR** [comment] 2016-09-16 16:36
I found the problem. Is not about reinstall or permissions. Is about multiple monitors

I know this is weird but i made the test right now. If the opentrack shortcut is on my second screen desktop when i hit start the program freezes, everytime in the last 10 tries! But if i put the shotcurt on my first screen the program start normally.

That is the most weird bug i ever seen

**Comment by sthalik** [comment] 2016-09-16 16:40
@FlyMakerBR indeed. But see if the build I linked helps. It has some HiDPI support and actually switches DPI awareness off for the whole program.

Also you can go to qt.conf in the install directory and use values of 0, 1, 2 for the DPI awareness parameter.

**Comment by FlyMakerBR** [comment] 2016-09-16 16:50
Tested on all experimental builds. All freezing on second monitor. DPI Awareness parameter not stopped the problem too

**Comment by sthalik** [comment] 2016-09-16 17:29
@FlyMakerBR what's the Windows version you're using?

**Comment by sthalik** [comment] 2016-09-16 17:30
I think it may have to do whether you allow the taskbar to be shown on the second display or not.

**Comment by FlyMakerBR** [comment] 2016-09-16 22:24
Windows 10 Pro 64 Build 10586

**Comment by FlyMakerBR** [comment] 2016-09-16 22:26
Tried to disable taskbar on second display and freezes still happening

**Comment by sthalik** [comment] 2016-09-21 16:32
@FlyMakerBR thanks for diagnosing the issue. It's serious and I woulda searched the software's components for a longer time to see what the hell's wrong.

I'm closing this issue but we can reopen if you wish to find out why it freezes on another display. We'd have to exchange multiple builds and debug info so it depends on how much time you want to allocate. I'm fine either way.

**Closed by sthalik** 2016-09-21 16:32 UTC
Labels: bug, next-build-2.3.0-rc12

**Comment by sthalik** [comment] 2016-10-06 07:19
@FlyMakerBR see #469. We're good now. Get a build at https://www.dropbox.com/sh/823dd4wyhixv5a7/AACB1Iqquvia_keD9jUY2qFBa
