### ISSUE TITLE
New feature: toggle for several output remap & mapping profiles

### ISSUE THREAD

**Issue by Maetharin** [opentrack/opentrack#671] opened 2017-08-06 13:56 UTC
Hello!
First of all, thank you for all the time and energy you put into this.

I wouldn´t know how easy this would be to accomplish, but I would appreciate it if I were able to switch between several profiles containing different output remaps and, less important, mappings.

To qualify further, I´m currently using an EDtracker Pro and have X output mapped to Yaw so I my virtual head moves accordingly when I look over my virtual shoulder.
It´s more than enough when only taking this action into consideration, but limits me when I´m looking for enemy planes and my cockpit layout impedes my sight.

If possible, I would like to be able to switch to one or more output remap profile so I can on the press of a button move my virtual head differently, f.e. by assigning X output to Roll input.

Thank you 

PS: Any news on multi source tracking? I´d love to supplement my EDtracker with f.e. Face API or IR tracking. It would make this feature completely unnecessary^^

**Comment by sthalik** [comment] 2017-08-07 08:54
We have multi-source tracking already, use the Fusion tracker.

We already have switching profiles planned. Arma players want it a lot. This is a duplicate of #609. I'm not keeping up with adding features as they're requested, there are now too many.

**Closed by sthalik** 2017-08-07 08:54 UTC
