### ISSUE TITLE
Aruco tracker crashes the Opentrack app when yaw angle is too high!

### ISSUE THREAD

**Issue by duamutefmc** [opentrack/opentrack#329] opened 2016-03-21 09:56 UTC
Hello there Stanisław! First of all congratulations on your amazing work on Opentrack, Accela and the Aruco implementation.

I'm trying to emulate TrackIR via Opentrack/Aruco with an Asus ROG G751JY laptop. Its webcam runs at 30fps, and the refresh frequency around 30hz when no light/exposure correction is used.

I've printed out a 100×100 mm Aruco marketn (id #800) and basically pasted it over my Samsung Gear VR visor cover.

When testing it (even before connecting the VR goggles!) it works like a charm *but* when I look too far towards the left or the right (yaw angle > 60°) the Opentrack app crashes.

Is there any way you can help me solve the issue?

Thank you in advance for your help! :)

**Comment by sthalik** [comment] 2016-04-06 15:38
@duamutefmc please send a video from the camera (not video of opentrack tracking, exactly what camera sees). Also compress the video, even .wmv is fine.

**Comment by sthalik** [comment] 2016-04-06 15:39
@duamutefmc you can record the yawing process then replay it with manycam to see if you have the right video.

**Comment by sthalik** [comment] 2016-05-06 07:39
I'm closing this issue after waiting for a month. @duamutefmc you can always respond with the data I need.

**Comment by Emton** [comment] 2016-05-16 06:43
Hey I've been getting a crash possibly similar to this, I can reproduce it every time practically all I have to do is do a real fast yaw movement as far as I can go and it crashes Opentrack. I'm on windows 8.1, I use PS3 eye cam, aruco tracker with EWMA filter. Getting the crash in IL2 BoS, it doesn't seem to crash doing the same movement within the opentrack program, also I'll try out arma 3 later to see if it crashes there.

**Comment by sthalik** [comment] 2016-05-16 07:15
@Emton please record the video from the camera that causes the crash, I'll replay it and trigger the crash in a debugger.

**Comment by Emton** [comment] 2016-05-16 08:26
How should I do this? I downloaded ManyCam free version but if I try to record in ManyCam I can't use the cam in opentrack.

**Comment by sthalik** [comment] 2016-05-16 08:54
Hey,

Enable the camera as a video source in manycam then you can both use and record in realtime. You can disable the manycam logo in effect options even in the free version.

Please compress the video in any way (Windows Movie Maker is the easiest), it shouldn't be bigger than 50 MB. People used to send GB-ish videos for no reason, just saying.

**Comment by sthalik** [comment] 2016-05-16 08:55
I forgot, then select "manycam video source" as the source in opentrack and it'll pass through the video while recording in real time. You can replay a video selecting it as a source in a similar fashion.

**Comment by Emton** [comment] 2016-05-16 11:47
Here try this and see if it works
http://www.filedropper.com/otbugcrashat42seconds
And here is the last image in opentrack for that crash
![otbugmanycamvid2](https://cloud.githubusercontent.com/assets/11396292/15288543/4ed27508-1b31-11e6-8afb-01705ed44ec8.PNG)
Here are some extra screen shots of crashes, most of them happen on the yaw access just as the tracker loses the image, also a lot of the time when the image gets lost there it takes the yaw value and puts it as the pitch, not sure if that is significant.
![otbugmanycamvid](https://cloud.githubusercontent.com/assets/11396292/15288649/e4b83b0c-1b31-11e6-83c8-8f609b392d5d.PNG)
![otbug](https://cloud.githubusercontent.com/assets/11396292/15288653/e4bd4598-1b31-11e6-80b5-8c6a9b1ecb2b.PNG)
![otbug2](https://cloud.githubusercontent.com/assets/11396292/15288652/e4bcc244-1b31-11e6-97e0-d7206f530ce9.PNG)
![otbug3](https://cloud.githubusercontent.com/assets/11396292/15288651/e4bc0656-1b31-11e6-8982-2746c5227d03.PNG)
![otbug4](https://cloud.githubusercontent.com/assets/11396292/15288650/e4b95c30-1b31-11e6-9798-2941deaf3860.PNG)
![otbug5](https://cloud.githubusercontent.com/assets/11396292/15288654/e4be186a-1b31-11e6-87e8-79e25e69f354.PNG)
![otbug7](https://cloud.githubusercontent.com/assets/11396292/15288655/e4c6c3c0-1b31-11e6-98c2-a2a641ecec06.PNG)

**Comment by sthalik** [comment] 2016-05-16 12:53
I have it crashed. This is the most important thing in fixing this. Thank you.

**Closed** 2016-05-16 13:42 UTC
Labels: bug

**Comment by sthalik** [comment] 2016-05-16 13:54
@Emton thank you. I couldn't fix it otherwise.

Here's a build with the fix before the next official installer: https://www.dropbox.com/s/8tny9aosmt19k0x/opentrack-2.3-rc49p0-aruco-fix.7z

**Comment by sthalik** [comment] 2016-05-16 13:54
Also paging @duamutefmc since he might want the build.

**Comment by duamutefmc** [comment] 2016-05-16 14:17
Hi all; well done. That's a good job. I just learnt about your kitten,
Stan, so my condolences. Having lost a few cats myself I know the felling.
=^_^=

**Comment by Emton** [comment] 2016-05-16 14:53
Cool I tried it out for a min and it hasn't crashed. I was just wondering do you know if there will be more image controls for the aruco tracker, maybe stuff like contrast, threshold or anything else that lets us tweak the picture?

**Comment by sthalik** [comment] 2016-05-16 15:36
@Emton If you're using the Eye we could only fake it by a hidden window and programmatic keypresses. The driver authors ignore the settings on purpose to peddle their paid driver.

We could fake it by a hidden window and fake keypresses but there are so many priority issues I won't start it for half a year or more.

If someone contributes code it's a different matter of course.
