### ISSUE TITLE
joystick input tracker issues since joy shortcuts introduction

### ISSUE THREAD

**Issue by runningman84** [opentrack/opentrack#267] opened 2015-11-15 21:37 UTC
I have two ore more joysticks connected to my machine. opentrack-2.3 rc21 forgets the selected joystick once I stop the tracking and open the tracker settings once again. So each time I open tracker settings I have to change the selected joystick to the right one (edtracker instead of x65) again.

**Comment by sthalik** [comment] 2015-11-16 08:26
What's your .ini value for `joy-guid`?

**Comment by sthalik** [comment] 2015-11-16 08:33
Is it consistent between runs?

**Comment by sthalik** [comment] 2015-11-16 08:50
Confirm works https://db.tt/r2dlFKZh, thanks

**Comment by runningman84** [comment] 2015-11-16 21:10
The version works but if I click on stop the application freezes.

**Comment by sthalik** [comment] 2015-11-21 18:07
it's in progress. we can apparently only have one joystick handle for the whole application at a time so a little refactoring is in order.

**Comment by sthalik** [comment] 2015-11-21 18:10
that is, joystick tracker will have to use core opentrack functionality that needs to exist to begin with.

**Comment by sthalik** [comment] 2015-11-22 15:08
Please confirm if this build works as advertised. In particular, I need to know whether multiple joystick selection is broken. I got only one stick so couldn't check it. @Len62 can you help?

The build - https://db.tt/1bXkwThn

**Comment by sthalik** [comment] 2015-11-22 15:12
Here's the same thing but without debug info. Smaller that way.https://db.tt/2DjeFOfO

**Comment by Len62** [comment] 2015-11-22 16:34
D/L the w/o debug install. I was able to assign buttons both from my joystick and throttle, which are separate USB devices. Settings were remembered by opentrack, as I started/stopped, open/closed the program multiple times. Did not experience any issues.

**Comment by sthalik** [comment] 2015-11-22 16:41
@Len62 thank you. I'm releasing rc21p1.

**Comment by sthalik** [comment] 2015-11-22 17:44
The joystick tracker should now also work when hotplugging/unplugging the stick's USB connector. I think it shouldn't crash on unplug during tracking in any cases. Report any issues.

**Comment by runningman84** [comment] 2015-11-23 20:40
The new version seems to work but the latency is really high and the movement is lags...

2.3rc20 works a lot faster.

**Comment by sthalik** [comment] 2015-11-24 00:05
@runningman84 is it for all trackers or only joystick input?

**Comment by runningman84** [comment] 2015-11-24 19:14
I do not have any other tracker

**Comment by sthalik** [comment] 2015-11-25 01:28
@runningman84 confirm this build works. There was this minor issue https://db.tt/dBrPzRWf

**Comment by runningman84** [comment] 2015-11-27 19:26
no opentrack-2.3-rc21p1-1-gf09ff29-20151125022606 suffers from the same problem...

**Comment by sthalik** [comment] 2015-11-29 11:01
Compare if https://db.tt/x06WJYor is any better, thanks.

**Comment by sthalik** [comment] 2015-11-29 11:01
oops

**Comment by sthalik** [comment] 2015-11-29 11:37
Use this one instead - https://db.tt/PW4OmoMd

**Comment by sthalik** [comment] 2015-12-02 11:40
@runningman84 is it any better in rc21p2?

**Comment by runningman84** [comment] 2015-12-02 14:11
I will report this night, sorry for the delay...

**Comment by runningman84** [comment] 2015-12-02 20:46
still very bumpy movement with opentrack-2.3-rc21p1-12-ga07eed2-20151129123438

**Comment by sthalik** [comment] 2015-12-05 15:38
@runningman84 I checked yaw using a throttle and there was no jerky movement. There were a few crashes in p2 that were fixed since then. Provide more info:

- is there low CPU usage as it should, or is it consuming one core or something
- is it also lagging with a stick/throttle as a controller

**Comment by runningman84** [comment] 2015-12-05 23:59
Just tested 2.3-rc21p3. The cpu usuage is about 3%. Yes it is also lagging using my x65 stick.

Funny enough the old release still works fine. I am running windows 10 x64. I can record a desktop view if this helps you?

**Comment by sthalik** [comment] 2015-12-06 00:03
How many USB joysticks do you have in total in the selection box?

Does disabling filtering help change anything?

How do you describe the erratic movement - is it pausing for fractions of a second while tracking or something else?

**Comment by sthalik** [comment] 2015-12-06 00:04
The old build didn't query for additional joysticks being plugged in or out. This is likely the cause.

**Comment by sthalik** [comment] 2015-12-06 04:47
I managed to remove the need for synchronization in most of the code. In particular, joystick tracker and joystick keybindings aren't using the same data anymore. This should help you out. Initial reports show no crashes or freezes.

If it's still stuttering, I'll remove refreshing the joystick list from asking for axis values.

@runningman84 build - https://db.tt/fvbAGatr

**Comment by runningman84** [comment] 2015-12-06 12:41
The latest build doesn't help either.

The movement is slow and doesn't look smooth.

I have a joystick and edtracker.

**Comment by sthalik** [comment] 2015-12-06 13:45
@runningman84 I'm not polling for new joysticks in this build - https://db.tt/tUBGEgRj

Any luck?

**Comment by runningman84** [comment] 2015-12-06 21:43
yes this build is working fine!

**Comment by sthalik** [comment] 2015-12-06 23:08
thanks!

**Comment by sthalik** [comment] 2015-12-17 22:01
#279 is the last one left. I'm closing this.

**Closed by sthalik** 2015-12-17 22:01 UTC
Labels: blocker
