### ISSUE TITLE
Z axis whilst yawing

### ISSUE THREAD

**Issue by forteh** [opentrack/opentrack#106] opened 2014-12-14 23:06 UTC
Hi,
Up until recently I used freetrack, however it just stopped being recognised in arma3 (for some inexplicable reason - I suspect it is due to a recent game patch) so I installed opentrack to test out against facetracknoir.  I very much prefer the gui and setup of opentrack, it also works incredibly smoothly ingame using the ps3eye and a 3 point ir clip.

I have an issue in that when yawing I get inputs on the Z axis, I bind this to zoom within arma so it is very frustrating to have the view keep zooming when looking around; freetrack never used to do this and seemed to isolate the individual axis movements a little better (I get movement is just about all axis when yawing). Is there something that can be done to stop this happening short of setting a large deadzone on the Z axis?

Additionally on freetrack there is functionality to increase the smoothing based on the percentage of Z axis applied, this works very well in arma as it stabilises the view when zoomed in. Again it possible to enable/implement this in opentrack?

**Comment by forteh** [comment] 2015-01-02 20:02
After 4 days of finally sorting the mother in laws computer!!! Repainting the bedroom I have a chance to check on these calibration axes :)

When I autocalibrate using yaw and pitch only I get the following results
x -111
y -75
z 73
The red cross appears roughly in the correct position of centre of neck rotation.

With +/-30° yaw applied
Tx     -10 with +30° yaw only
Ty     +/-4
Tz     +/-10
Pitch +/-1 (negligable)
Roll   +/-12°

With +/-30° pitch applied
Tx     +/-1 (negligable)
Ty     +/-6
Tz     +10/-5
Yaw   +/-1 (negligable)
Roll   +/-1 (negligable)

With +/-30° roll applied
Tx     +5/-15
Ty     +10/-14
Tz     +/-2 (negligable)
Yaw   +/-1 (negligable)
Pitch  +/-1 (negligable)

Making x and y positive eliminates most of the cross axes motion.
Then Making z negative eliminates the rest of the cross axes motion apart from the roll when yawing.  Altering the z doesn't seem to massively affect the roll when yawing, it might be to do with the dimensions of my model.

Hope that all makes some sort of sense!

**Comment by FlyingCircus-** [comment] 2015-01-03 00:48
We all agree about the x coordinate inversion, but it doesn't mean the other axes couldn't be also inverted as suggested by forteh. I made tests with x and z coordinates (somehow assuming the sign of y axis was unmistakeable), and I got negligible differences when inverting the z coordinate. I will try to confirme what forteh says when I have a chance.

**Comment by forteh** [comment] 2015-01-03 09:07
I should have added that whilst inverting polarity on all three axes cures the cross axis motion, it puts the red cross approximately at the top of my head.

I'm not 100% sure if it is inline with my neck or off to one side, without removing the visible light filter from the camera I can't tell. If I find time from decorating I will look into it.

Perhaps if the autocalibration results are inverted and also the dimensions for the position of the red cross it would be correct.

Does the auto calibration extrapolate the z calibration from the point movement whilst yawing/pitching? The 75mm dimension would be accurate for my head/model so it would appear to work apart from the polarity.

Can I suggest that the autocalibration pane is annotated that only pitch and yaw should be inputted whilst calibrating and that z can be manually altered if the auto gets it wildly wrong. Also a note stating that the calibration dimensions are from the roll centre of the head and an annotated skull diagram with the axis polarity would be useful :)

**Comment by FlyingCircus-** [comment] 2015-01-04 19:46
@forteh The position of the red cross suffer from the same inversions as the centering values: I bet the red cross was on one side of your head when you set them up manually. I made my own tests today and I barely could notice any difference when inverting y and z centering coordinates (maybe because those values are very close to 0 anyway), but I'm inclined to think forteh is right and all axes should be inverted.

**Comment by sthalik** [comment] 2015-01-05 21:29
It looks like @forteh is right here too. Shows on the videos.

**Comment by forteh** [comment] 2015-01-06 09:54
Good stuff :)

On a slightly unrelated issue....

I am building a head tracking setup for my brother in law for use in elite, he doesn't use a headset so going to make a cap mounted unit.  Are cap mounted point models any worse than clip?  I can probably design a clip that will work with a cap but if the traditional cap models are similar tracking performance it would be simpler to implement.  Can anyone advise?

**Comment by Trooph** [comment] 2015-01-06 09:57
Noob question. Is it possible to download just those 2 changed files switch them in RC7 and start testing?

**Comment by FlyingCircus-** [comment] 2015-01-07 10:31
@forteh From my experience with freetrack I know the cap model is perfect for IR tracking. It's actually a very similar setup to the clip model, more symetric (worse) but with dots usually separated by higher distances (better). However, current OpenTrack version presents the issue discussed in #112 for cap models, which hasn't an easy fix for the time being.

@Trooph Those are source c++ files, surely they need to be compiled with the rest of them in order to get a working build, I wouldn't try...

**Comment by forteh** [comment] 2015-01-07 11:28
Well I would prefer to set him up with opentrack over freetrack so will probably fabricate a 3point clip that attaches to the side of the peak.  Infact, thinking about it I just bought 10 ir leds so have enough spare to build both options and he can mix and match; I am also making a clip for another friend but I know he uses headset so can use the spare clip if the 3point cap works well enough :)

**Comment by forteh** [comment] 2015-01-08 15:14
For further information I had a chance to properly test it out in arma3 last night and with the inverted autocalibration settings it works perfectly.  Tracking is very responsive, movement is super smooth and there is no cross axis motion evident at all, very happy :)

**Comment by sthalik** [comment] 2015-01-08 16:34
@forteh please check rc8 if inverting after calibration is no longer necessary. I've tried @FlyingCircus-' video but it isn't representative of all use cases. Calibration code from 2.2 is use pretty much verbatim but there could be an error lying out anywhere, typical of programming.

**Comment by forteh** [comment] 2015-01-08 16:58
I'll try to test it out later on tonight.
Is it recommended to reconfigure the settings from scratch or should it be sufficient to load in my profile config from RC7?  Either way I will retest the autocalibration and see how it works in comparison to my current RC7 setup.

**Comment by sthalik** [comment] 2015-01-08 17:36
No need to redo any settings. Their list is stable in 2.3 for a while now.

**Comment by forteh** [comment] 2015-01-08 20:17
@sthalik, I've had a quick play with RC8 and initially it was all over the place with Tx and Tz fixed to -99 on game data and no recorded raw movement.  Running the auto calibration didn't fix this, neither did setting my working RC7 calibrations.

Restarting opentrack released the Tx (but still locked the Tz), restarting a second time seemed to initialise all axis and it autocalibrated correctly with no cross axis movement.

The autocalibration still seems to be inverting the position, it is giving me -110x; -75y; 82z.  In reality the reference point is 110mm to the left of centre, 75mm above centre and 82mm forwards of centre (towards the camera).  Whilst the it is tracking correctly the point display window is still showing it inverted as per the attachment.

![opentrack rc8 calibration](https://cloud.githubusercontent.com/assets/10188849/5669876/447f28dc-9773-11e4-9beb-6b8087f132c9.jpg)

**Comment by sthalik** [comment] 2015-01-08 20:50
Hey, you haven't said which of XYZ are inverted on display. Is it just Y or Z too? Please specify.

**Comment by sthalik** [comment] 2015-01-08 21:02
As for your first issue, autocalibration didn't reset its values to zero prior to calibrating. Unless these values are zero, the result is nonsense. I'll fix that in another update batch.

For the second issue you haven't said which of the XYZ directions are wrong. Please specify.

**Comment by forteh** [comment] 2015-01-08 21:03
All three axes are inverted compared to my Rc7 manual settings (110x; 75y; -75z) which work perfectly. The Rc8 auto calibration results in the clip being properly calibrated and gives equal motion results to my Rc7 settings, however the red reference position is inverted, it should be on the other side at the bottom. 

If I manually invert all three axis the red point is displayed in the correct physical location but it breaks all of the calibration.

My earlier comment on an annotated skull diagram showing which is positive/negative on each axis might go some way clarify the calibration. I will knock up a model in solidworks tomorrow at work and give you an image to demonstrate what I mean :)

**Comment by forteh** [comment] 2015-01-09 10:27
Something like this :)
The white ball is to represent the reference point of the clip.
If you want to use these renders feel free, if you want to make any changes to the model then I can.  I'm not sure if the axis polarity I have set is correct with the calibration in opentrack but it is quick and easy to edit the text and re-render the images.

![icon isometric](https://cloud.githubusercontent.com/assets/10188849/5678374/b90ab088-97e9-11e4-9c63-51b502e4c096.JPG)

![icon front](https://cloud.githubusercontent.com/assets/10188849/5678376/bb46929a-97e9-11e4-993e-0bfcf6a7edac.JPG)

![icon side](https://cloud.githubusercontent.com/assets/10188849/5678377/bcdee33c-97e9-11e4-865d-c1a14a05eb65.JPG)

**Comment by forteh** [comment] 2015-01-09 10:53
Or perhaps this works better? Now you can reference in relation to the face which axis the reference point is +/- on.
I've flipped the X axis polarity as I realised it didn't align with how the raw tracker reads.

![icon isometric rev 1](https://cloud.githubusercontent.com/assets/10188849/5678726/18dc8948-97ed-11e4-837b-333bfbd5183a.JPG)

**Comment by sthalik** [comment] 2015-01-18 12:47
There's something wrong on the calibration side, not the display side. Having the red cross close to the middle of the screen results in -16 units of X. It should be very close to zero in that case. The cross positioning works fine, as in the zero case it occludes the LED's green cross.

That said, I need more time with it that involves thinking, not flipping the signs and hoping the issue's finally gone as it was.

We don't need to explain the sign convention used since when it all works, no ambiguity on user's side will occur.

I could use a calibration video with working pitch movement, along with model's measurements. The one I already have, pitch barely has frames.

**Comment by forteh** [comment] 2015-01-18 19:46
I'll have a play later and see if I can get a video of the calibration with pitch and yaw :)

Surely the position of the red cross relative to the centre of the screen is immaterial as this depends on where the camera is in relation to the clip. The dimensions shown above are correct once the polarity of the axes are reversed.

**Comment by forteh** [comment] 2015-01-20 00:07
Here is a capture of the calibration, as said it results in good tracking and it all works perfectly.

https://www.dropbox.com/s/rgkcimuvgyod6pc/opentrack%202.3-rc8%20calibration.xesc?dl=0

With a little further testing I can confirm that the red cross position is on the correct side of the head (the view is mirrored on a ps3 eye but I couldn't tell that with the visible light filter fitted).

What do the model position numbers actually represent?  Is it the distance from the centre of rotation to the reference point or vice versa?  What datum are the dimensions set against?  What is the axis polarity meant to be?

If the polarity is meant to be inline with the raw tracker data then the autocalibration says that the clip is 65mm behind the centre of rotation or is it the other way round?  In reality it is 65mm forward (negative on Tz).  Likewise the Y position is apparantly inverted (when compared to the physical model), the calibrated dimension is correct but the reference cross is not in the right place (it should be shown 200mm lower; 100mm below the centre point not the current 100mm above).  Without an axis diagram and/or an instruction on how to check the dimensions it is very confusing as to what the measurements actually refer to.

**Comment by sthalik** [comment] 2015-01-24 15:01
@forteh The unit of model coordinates is the same as the one used to specify model's size. It's relative to the reference point.

Regarding axis sign, pose estimation uses a different set of coordinates as per this comment
<code>    // translate rotation matrix from opengl (G) to roll-pitch-yaw (E) frame
    // -z -> x, y -> z, x -> -y
</code>
and using it verbatim Just Works. Flipping a sign would cause a rotation to influence given DOF the other way. This part I haven't noticed till now, hence initial confusion.

The rotation basis code respective model position is a mess as per above quoted comment. The confusion is partly alleviated by changes being visible in realtime. I don't consider it a priority issue at all hence. I'm willing to fix it to the point of calibration working, and cross signs correct. But spending any more effort on the model position functionality is just a waste of developers time.

**Comment by sthalik** [comment] 2015-02-01 03:10
@forteh @FlyingCircus- please recheck this in rc9.

**Comment by FlyingCircus-** [comment] 2015-02-01 10:56
I really don't have time for anything today. Anyway, I tested briefly and noticed the automatic centering at the beginning gives me (99, 99, 99) in the translation axes, which makes it unusable until you manually press the centering key again. Dynamic pose resolution on and off didn't have any appreciable effect on the clip model (but you know it's the cap model the conflictive one).

Finally, regarding the reference point/red cross I'm not so sure about your statement: I believe the red cross shouldn't go to the middle of the screen when centering the view (considering TX=0 in the model dimensions) since centering only affects to game values and not the raw values. Shouldn't it still be inverted in the x axis?

**Comment by sthalik** [comment] 2015-02-17 04:54
@FlyingCircus- red cross has nothing to do with centering in mapping menu. Calibration is done in PT and so it affects both raw and game data.

**Comment by FlyingCircus-** [comment] 2015-02-17 08:57
@sthalik I'm afraid we got caught up in semantics, since I was taliking about manually centering the view by pressing the "center view" shortcut. I was arguing against the statement: "Having the red cross close to the middle of the screen results in -16 units of X. It should be very close to zero in that case", which I still disagree. Sorry if I'm mistaken, but the red cross should be located in the origin of translations-rotations with respect to the "referenece dot" of each model, instead of the absolute origin of coordinates (middle of the screen). Therefore, our feedback about X axis inversion in the calibration coordinates may still be right (or wrong, who knows, but due to different reasons).

**Comment by sthalik** [comment] 2015-02-17 09:02
By virtue of the cross returning close to zero in the middle of the screen it's known that X sign is right. Otherwise it'd be drawn to the other side of the model.

Coincidentally I tested it again on your sample video and the model center now shows on the side of your head, not on the other.

I fail to see a clear rationale for translation originating from the middle point, not the model center.

**Comment by FlyingCircus-** [comment] 2015-02-18 08:52
Even so, just for testing purposes Could you make a build with the model x coordinate inverted? That way I can make it fit to the visual center of rotations/translations and compare the two builds thoroughly. Don't rely on my former callibration settings, I'm not sure they were right.

**Comment by sthalik** [comment] 2015-03-13 21:56
@FlyingCircus- It's frustrating for me to make so many round-trips with binary builds and conflicting responses. What I'd need is a clip calibration video. The video you gave me long time ago doesn't calibrate on pitch axis, points bleed over each other and there's no tracking there. Without pitch information Y model calibration won't be correct.

**Comment by forteh** [comment] 2015-03-14 08:14
@sthalik- was my calibration video above ok? I've been using rc9 since release with no issues, in my opinion the red cross still needs to be flipped in the Y axis if it is meant to represent the base of skull.

Only other comment on rc9 is that you need to manually centre the tracker once it's started otherwise the z translation is fixed at a certain point and is unresponsive until reset.

This seems to have got very popular recently and understand you have a million things to do and no time to do them! Appreciate all the hard work :)

**Comment by sthalik** [comment] 2015-03-17 14:39
@forteh no, that's not what I need. To test calibration I need a stream from the camera, just like opentrack sees it, so that I can plug it into a virtual webcam.

Center in rc9 happens automatically once a valid pose is received for the first time. The setting itself is a little buggy, and hard to disable. It's fixed in time for the next rc.

**Comment by forteh** [comment] 2015-03-17 17:11
So a video of the same movements but with the cleye test (ps3 camera test software) rather than opentrack? I presume you need a visible light video so not with the filter on the camera, I have a spare ps3eye so I'll see what I can get later :)

**Comment by forteh** [comment] 2015-03-20 20:04
Try this, not sure why it's playing back really quick but I guess you are able to slow it down to suit :)
https://www.dropbox.com/s/lqqb6jmyxd983ne/opentrack-2.3-rc9%20calibration%20test.avi?dl=0

Now I've had a chance to test it without the visible light filter the is the camera view in opentrack.

![opentrack-2 3-rc9 calibration test](https://cloud.githubusercontent.com/assets/10188849/6759944/0f95da16-cf3c-11e4-8991-06f8b19a2869.jpg)

As you can see the red cross is above my head and if it were flipped in the Y axis would be positioned about right with the base of my skull.

Does that help any?

**Comment by sthalik** [comment] 2015-03-31 04:06
The video helps a lot. Automatic calibration returns model's center to the left and slightly below. It should be fine.

**Comment by sthalik** [comment] 2015-03-31 04:07
I'll release rc 10 later though as FreePIE app for Android has delays.

**Comment by FlyingCircus-** [comment] 2015-03-31 08:23
Glad to see you're making progress. I'm quite busy these days, but I guess I would always make time for some tests if you need them. Don't mind to ask

**Comment by forteh** [comment] 2015-03-31 12:42
Glad it helped!
As I've said before the rc9 autocalibration seems to work very well although I'm still a little confused as to where exactly the red cross is meant to be - I always assumed that it was intended to denote the calibration centre (which as you say is to the left and below on the photo, physically to the right and below if you discount the mirroring of the ps3eye image).

Looking forward to testing the next iteration :)

**Comment by sthalik** [comment] 2015-04-02 11:28
@forteh it's as you say, calibration center.

rc10 has to wait, in meantime you can see <<https://www.dropbox.com/s/ok73ddag92ciym0/opentrack-2.3-PLUS-hatire.7z>> that has all the PT changes.

**Comment by FlyingCircus-** [comment] 2015-04-03 10:02
I have been testing the version linked in the previous post with PointTracker, so I could benefit from your reworked coordinates for the model position and calibration. It seems all good this time, having the red cross rightly located helps a lot to minimize any cross axes influence you may get.

New Accela labels makes all more understandable. However, I think there’s some small room for improvement which would make it completely perfect:

In some old thread we discussed the slow drift some of us experienced after reaching a new pose (that one you end up talking about subpixel rendering, which I agree it seemed beside the point). I still get that effect and apparently it’s caused by very small variations of the dots location (<1º in the raw coordinates but they are multiplied to several degrees due to the curves gain). I believe that effect could be dealt with the former Accela deadbands, but with the new merged settings makes it difficult to accomplish. Any way we could get rid of this issue in the future?

**Comment by FlyingCircus-** [comment] 2015-04-03 10:05
To be more precise, those small variations seem to be caused by the own hysteresis of the webcam sensor more than real movements (hence the talk about rendering issues)

**Comment by sthalik** [comment] 2015-04-03 10:06
@FlyingCircus- start by setting smoothing to 100 ms, see if it works, if does, try if you can decrease smoothing somewhat. The delay is effectively smaller than 100 ms due to how EWMA works.

You can play with sensitivity too, but sensor noise is better removed with EWMA.

**Comment by FlyingCircus-** [comment] 2015-04-03 10:13
Smoothing always helps but those are still dynamic settings more than deadbands. The thing is I preffer to avoid the lag when you increase smoothing (once you get used to semiinstantaneous movements you don't want to get back). I would try EWMA, despite I have been liking Accela much more since Mk4

**Comment by sthalik** [comment] 2015-04-03 10:30
I referred to EWMA as the smoothing setting which is using EWMA for averaging.

Smoothing over 100 ms isn't suitable for gameplay, just the general idea of reducing noise. Can you get good enough response time with smaller smoothing time? Keep in mind 16 ms or less isn't filtering 60 FPS video at all.

The EWMA filter is trying to estimate average noise by how much movement there is. I'm not sure how helpful that is.

**Comment by FlyingCircus-** [comment] 2015-04-03 10:48
What I'm looking for is a way to limit the raw data resolution so noise is not averaged but discarded. For example, if I could only allow raw rotation increments of 1.5º most of my trouble would go away.

**Comment by sthalik** [comment] 2015-04-03 10:58
That way it could only work badly. With deadband setting closer to one degree it was obviously visible how gameplay didn't react to minor view adjustments.

I'm confident the filter can work fine without requiring addition of such settings.

To get rid of small amount of noise it was necessary to have huge deadbands, more inconvenient than EWMA here. As amount of noise increases, deadband becomes not practical.

**Comment by FlyingCircus-** [comment] 2015-04-03 11:07
@sthalik Mmm... I'm not sure if our exprience is different because our setups also are. I sit very close to the webcam so even the slighleest rotations are always translated to several degrees of raw data. However I get noise below the 1º of raw data (which is inapreciable since OpenTrack doesn't show those decimals, but is visible as a single pixel movement of the green crosses and several degrees in the game values).

**Comment by sthalik** [comment] 2015-04-03 11:13
@FlyingCircus- I used the paper marker tracker which has more noise inherent in the process. The response was good enough for some gameplay. If anything, your experience with less noisy LED tracker should be less laggy.

One thing you can do is make less sharper mapping settings. If one degree of raw movement corresponds to too much of game movement, the filter can't translate it into precision as there's none to begin with.

**Comment by FlyingCircus-** [comment] 2015-04-03 11:19
Don't get me wrong, my setup works great. I'm just making suggestions for future improvement. I believe raw data deadbands would be a nice addition, if you share the same view at some point I will be happy to see it implemented.

**Comment by forteh** [comment] 2015-04-04 18:05
@sthalik - I have tested the build above and it works perfectly, the red cross is exactly where I would expect it to be :)
Consider this issue closed now if you want.

**Comment by sthalik** [comment] 2015-04-04 21:31
@forteh this is great news! Thanks for the confirmation.

**Closed by sthalik** 2015-04-04 21:31 UTC
