### ISSUE TITLE
game data pauses randomly after few dozen minutes

### ISSUE THREAD

**Issue by Shadoware** [opentrack/opentrack#255] opened 2015-10-13 00:24 UTC
I was using rc 17 which works very good for me. I tried rc 19 and it seems more smooth but in dcs a-10, suddenly it stops! The soft doesnt crash but the game stops receiving information from opentrack and I cant change the view. If I use rc 17 I dont have any problem.

I use windows 8.1 64-bit and I play DCS A-10 on Steam. This problem occurred with non installed version of Opentrack. I didn't try the installed version.

**Comment by sthalik** [comment] 2015-10-13 02:09
Can you reproduce? How long does it take for it to break?

**Comment by sthalik** [comment] 2015-10-13 02:17
Do you use headtracker.dll?

**Comment by Len62** [comment] 2015-10-13 03:09
I experienced this once myself. OpenTrack just stops, doesn't crash, still reading points but no output. I'll check again to see if it does it again.

**Comment by sthalik** [comment] 2015-10-13 03:17
opentrack has no output shown in the UI or just doesn't pass to game?

Do you have headtracker.dll or use freetrack as-is?

**Comment by Len62** [comment] 2015-10-13 03:40
No output in the UI. I can click stop, then start, and it starts again. Using freetrack. I just ran it again for about 30 minutes w/o any issues.  Will do some more testing and report back.

**Comment by MathijsG** [comment] 2015-10-13 12:02
I maybe encountered the same in ArmA II. Will play, ehh investigate further.

**Comment by Len62** [comment] 2015-10-13 12:13
Just had the issue again after about 45 minutes of running. If I switch to the UI, the points are tracking, the raw data is displaying properly, but game data is stuck on 0.

**Comment by petsild** [comment] 2015-10-13 12:44
I have the same problem stopping the data the rc19p1. So far did this to me randomly around 30min Rise of Flight and DCS, will only help to put the stop and run again. I use Win7 home premium 64-bit and the games are non steam. I'm trying to still rc18 defect has so far not exhibited.

**Comment by Len62** [comment] 2015-10-13 13:43
One more time after around 40 minutes in BOS. Notice the game data values in the pic. Interesting since I have TY and Roll disabled.
![rc19p1](https://cloud.githubusercontent.com/assets/10486813/10456311/b012bfaa-718e-11e5-9b44-e48aa4b66c11.PNG) Points still track and raw data working. Just the game data locking up.

**Comment by sthalik** [comment] 2015-10-13 14:28
try press toggle keybinding. it maybe can trigger on its own so bind it and report back.

**Comment by petsild** [comment] 2015-10-13 14:33
I will add too the picture just after the failure time 35 min after power up.
![otdata](https://cloud.githubusercontent.com/assets/13926997/10457799/ff3f0a1e-71c7-11e5-9b23-bdd8571cf09c.JPG)

**Comment by sthalik** [comment] 2015-10-13 15:02
each of you please tell if you have zero and our toggle bound

**Comment by Len62** [comment] 2015-10-13 15:10
Yes, I have both bound. After it locks-up toggle does not have any effect, zero will re-set game values to zero.

**Comment by petsild** [comment] 2015-10-13 15:24
Exactly as he wrote Len62.

**Comment by Len62** [comment] 2015-10-14 03:16
Update, ran opentrack for a couple of hours this evening w/o any problems, no lock-ups, no glitches. Will test some more in the morning.

**Comment by sthalik** [comment] 2015-10-14 06:16
@Len62 could it be that you haven't had toggle/center bound but now you have?

**Comment by sthalik** [comment] 2015-10-14 07:53
there's no check whether keybinding is disabled. maybe that's the cause. control space or some other key combination could generate an ASCII zero.

**Comment by Len62** [comment] 2015-10-14 08:56
No, all 3 of the bindings were set. I'll have another go with it shortly and see what happens.

**Comment by Len62** [comment] 2015-10-14 10:27
Ran another session around 60 minutes w/o any issues. Strange to say the least.

**Comment by sthalik** [comment] 2015-10-14 13:06
this can also be filter-related. I need to install Windows again, stay tuned.

**Comment by Len62** [comment] 2015-10-14 15:13
Had a lock-up after about 30 minutes just a short while ago. Auto-threshold maybe ? I really didn't check to see when I had it enabled. I'll do some more checking and report back.

**Comment by Len62** [comment] 2015-10-16 13:23
Auto-threshold does not appear to be connected to this issue. The lock-up is still intermittent and I can't really get any idea what causes it. Last night experienced a couple of lock-ups, but this morning none while running for about 60 minutes.

**Comment by sthalik** [comment] 2015-10-17 05:09
Try this one https://www.dropbox.com/s/pwg1srxazw6ydft/opentrack-2.3-rc19p1-9-gf314ef0.zip it has two speculative fixes.

If it works for a few days for you guys I'll release p2.

**Comment by petsild** [comment] 2015-10-17 07:46
Hi, I already wanted to write that after an hour of testing is in order, but then chobotnička again stopped. But it may now be repaired by the center and the movement again works. Yesterday I used mp on rc19 and everything worked well without stopping the 3h in a row. Friends make the image even once, did not stop for the entire time of use rc19p1, I have no idea what's causing it. Much I appreciate your efforts and perfect support thank you. Pet

**Comment by sthalik** [comment] 2015-10-17 07:51
so it's the filter 99%.

**Comment by sthalik** [comment] 2015-10-17 09:50
Good morning Vice City!

https://db.tt/Py90BwBL

**Comment by MathijsG** [comment] 2015-10-17 11:45
I had it once yesterday in Rise of Flight. After restarting it and flying for at least the same length, no problems then. I have auto treshold set to off.

**Comment by sthalik** [comment] 2015-10-17 12:13
@MathijsG try the today's build. I think I know where the problem resides, now.

**Comment by Len62** [comment] 2015-10-17 12:20
Ran the latest build approx. 90 minutes w/o any issues.

**Comment by sthalik** [comment] 2015-10-17 14:11
@Len62 how long was the loss?

Does it lock up completely with no recourse other than recenter still?

**Comment by sthalik** [comment] 2015-10-17 14:18
@Len62 are your model coordinates accurate? It's likely that PT submits broken coordinates for some reason.

**Comment by Len62** [comment] 2015-10-17 14:43
The loss is only momentary, a second or less most times, like a blink. No recent lock-ups, just the "blink". I'll double check the model coordinates and get back with you.

**Comment by sthalik** [comment] 2015-10-17 14:51
@Len62 does the loss merely drop frames or does it reset to another pose?

**Comment by Len62** [comment] 2015-10-17 15:03
Just drops frames. I went back and checked my set-up, model coordinates were fine. I did change the camera pitch angle, as I recently raised my monitor up some, and re-did the calibration. Seems to be working fine right now, haven't had any issues since I re-checked all of my settings.

**Comment by petsild** [comment] 2015-10-17 15:18
I tested the latest build but still the same problem. The last time happened in a completely direct view.

**Comment by sthalik** [comment] 2015-10-17 15:22
@petsild do you have opentrack-2.3-rc19p1-23 in the title bar?

**Comment by petsild** [comment] 2015-10-17 15:27
Yes rc19p1-23

**Comment by sthalik** [comment] 2015-10-17 15:29
And you need to center then? I find that hard to see now that each code path in tracker pipeline checks for invalid values.

**Comment by petsild** [comment] 2015-10-17 16:04
After centering the turn continues normally.

**Comment by Oakshios** [comment] 2015-10-18 01:53
I have had this issue using Freepie with Freetrack enhanced protocol.  Will try with the newest build and report back.

**Comment by sthalik** [comment] 2015-10-18 03:40
@Oakshios unpack the .zip anywhere you want and run it: https://db.tt/Py90BwBL

It's important knowing that FreePIE gives the same result. It's definitely mapping- and filter-related.

**Comment by sthalik** [comment] 2015-10-18 03:52
New build with more checks in Accela and mapping editor (involves Accela too) - https://db.tt/D5luNvTe

**Comment by Oakshios** [comment] 2015-10-18 04:36
Thanks for the zip.  Installed and will let you know if I notice further freezes.  Let me know if there is any other config info you might need to help narrow down the issue.

**Comment by sthalik** [comment] 2015-10-18 04:39
Just make sure model coordinates and camera FOV are ok.

**Comment by Oakshios** [comment] 2015-10-18 06:20
Using rc19-30 I am still getting freezing.  When it happens sometimes the coords lock in some random crazy position.

**Comment by sthalik** [comment] 2015-10-18 07:40
Are you using dynamic pose resolution? Here's a fix relating to dynamic pose and this problem. https://db.tt/ixlixsbN

**Comment by Oakshios** [comment] 2015-10-18 08:06
I am not sure what dynamic pose is.

**Comment by sthalik** [comment] 2015-10-18 08:07
PT settings -> camera -> dynamic pose resolution

**Comment by Oakshios** [comment] 2015-10-18 08:49
I found that setting, but I don't use that tracker.  I use freepie imu on my Galaxy Note 4 and the freepie UDP tracker to accept the raw data.
![capture](https://cloud.githubusercontent.com/assets/10933276/10563296/23a16622-7542-11e5-9d57-3aacd5f9a86d.JPG)
![capture2](https://cloud.githubusercontent.com/assets/10933276/10563299/38ce8c6e-7542-11e5-9214-ab28dac999d3.JPG)
![capture3](https://cloud.githubusercontent.com/assets/10933276/10563302/5a0cab04-7542-11e5-88c8-06d10a15a9eb.JPG)
![capture4](https://cloud.githubusercontent.com/assets/10933276/10563303/6c7d55cc-7542-11e5-947c-ff5df7845dc3.JPG)
![capture5](https://cloud.githubusercontent.com/assets/10933276/10563304/7ad57078-7542-11e5-8bdb-646bbf65b899.JPG)
![capture6](https://cloud.githubusercontent.com/assets/10933276/10563306/8e8455da-7542-11e5-9d1f-45d4da11f701.JPG)
![capture7](https://cloud.githubusercontent.com/assets/10933276/10563307/a0db00d0-7542-11e5-8283-1630182ef5b8.JPG)
![capture8](https://cloud.githubusercontent.com/assets/10933276/10563313/dc9710aa-7542-11e5-9e8a-0129fb9532ac.JPG)

**Comment by Oakshios** [comment] 2015-10-18 08:52
I am calling it a night on my end.  Will check back later today.

**Comment by sthalik** [comment] 2015-10-19 05:35
I need everyone's input on https://db.tt/ixlixsbN, especially on PT tracker.

**Comment by Len62** [comment] 2015-10-19 10:06
I still get the occasional tracking loss,  and I did get a hard lock-up once last night, and stop did not work, clicking the X to close the window caused it to crash completely. I'll be doing some more testing over the next hour or so.

**Comment by sthalik** [comment] 2015-10-19 11:09
note to self: check valgrind

**Comment by Len62** [comment] 2015-10-19 11:18
Here's a short video showing what is happening. 
https://www.dropbox.com/s/8cpcpavla92gsp9/opentrack.mp4?dl=0

**Comment by Len62** [comment] 2015-10-19 14:33
I deleted the previous post and I have to apologize to you. I did some checking on my clip and discovered that one of the power wires had a connection that was failing intermittently, enough to cause the LEDs to turn-off sporadically when I pitched down. Should have thought to check this in the first place. I soldered up a new connection and everything works fine. Sorry.

**Comment by petsild** [comment] 2015-10-19 15:23
My cable is fine, after testing 3x2h and efforts to simulate by the conditions of the freeze is build 36 stable.

**Comment by Oakshios** [comment] 2015-10-19 15:33
I will confirm stability with new build on my configuration when I get home from work.  Thanks for hunting down this issue sthalik!

**Comment by sthalik** [comment] 2015-10-20 03:28
@Len62 do I understand in the video (thanks for not removing it just yet) it fails interminnently but never forever until recentering?

@petsild do you mean that it works or it doesn't?

**Comment by sthalik** [comment] 2015-10-20 03:28
When works for everyone I'll update patchlevel.

**Comment by sthalik** [comment] 2015-10-20 03:32
@Len62
> I deleted the previous post and I have to apologize to you. I did some checking on my clip and 
> discovered that one of the power wires had a connection that was failing intermittently, enough to 
> cause the LEDs to turn-off sporadically when I pitched down.

Your interminnent failure helped cause the error to occur, which is good. PT shouldn't break forever like it does in the current official build.

**Comment by sthalik** [comment] 2015-10-20 03:32
Paging @MathijsG

**Comment by sthalik** [comment] 2015-10-20 03:41
Note to self: update trackhat branch when confirmed.

**Comment by MathijsG** [comment] 2015-10-20 07:50
I will check soon with the new build. With the build of this problem I sometimes had that I needed to stop start the tracking and then it was all okay again, and sometimes the whole program hung stuck.

Will test further, but I'm not allowed to game that much when I'm supposed to study :-P.

**Comment by petsild** [comment] 2015-10-20 16:01
@sthalik  do you mean that it works or it doesn't?

Yes works without issue.

**Comment by Len62** [comment] 2015-10-20 18:23
Have run the 19p2 for about 3 hours. Only had one lock-up around five minutes in, center re-set it, and if has been fine since.

**Comment by MathijsG** [comment] 2015-10-20 18:31
Already had a lock up of the octopus with RC19 after just about 10 minutes. Restarted the tracking (just hit stop and start again) did not happen again, yet.

**Comment by sthalik** [comment] 2015-10-20 19:50
that's bad. we can't have any lookups. stay tuned. are you all using pt?

**Comment by MathijsG** [comment] 2015-10-20 19:51
I am

**Comment by Len62** [comment] 2015-10-20 20:00
I am also.

**Comment by sthalik** [comment] 2015-10-20 20:11
Can you try to reproduce the issue without any filter at all? Just for testing.

**Comment by Len62** [comment] 2015-10-20 21:06
Ran it for about 40-45 minutes w/o any filter, did not experience any issues.

**Comment by sthalik** [comment] 2015-10-20 22:24
@MathijsG can you confirm too please?

**Comment by sthalik** [comment] 2015-10-20 22:26
damn i ran outta sata connectors. the horror. stay tuned gonna take some time...

**Comment by sthalik** [comment] 2015-10-22 07:36
Try this one guys - https://db.tt/s7S5pvAk

There are no functional changes but I changed build options. No promises.

**Comment by sthalik** [comment] 2015-10-22 07:36
Note to self: if still messed up, disable math optimizations fully for testing.

**Comment by Len62** [comment] 2015-10-22 09:47
During a short session, around 30 minutes, had two lock-ups, but centering got it working each time.

**Comment by samkatakouzinosracing** [comment] 2015-10-22 18:12
http://www.twitch.tv/samkatakouzinosracing/v/21848972?t=01h38m13s 
This shows behaviour similar to this thread. Head tracking fails and makes in game head turn hard right. This was in an iRacing practice session. 
Up until this point head tracking would jam view until I pressed bounds keys in attempt to correct. Straight after this I changed out to previous rc18 version. 
At 14m mark you can see me start race where I'm having difficulty with head tracking.

**Comment by Oakshios** [comment] 2015-10-22 19:45
@samkatakouzinoracing  The updates in this thread above still seem to have a freeing issue periodically, however you should be able to recenter the view and content tracking again.

**Comment by petsild** [comment] 2015-10-22 19:57
Unfortunately the problem on the p2-1 still takes the extra OT crash not responding and the task manager to close the Trackir.exe manually.

**Comment by sthalik** [comment] 2015-10-22 20:57
Here's a build with excessive math optimizations: https://db.tt/YYuW6riW

**Comment by Len62** [comment] 2015-10-22 22:32
This was a strange one, locked-up twice, centering re-set everything, locked-up again and yaw axis got switched, stopped, re-started and it was fine for the next 45 minutes or so.

**Comment by sthalik** [comment] 2015-10-23 08:27
Note to self: valgrind this time.

**Comment by petsild** [comment] 2015-10-23 22:01
Today me OT failed 3x in the dogfight, until they find a cure I will be on MP to use the back rc18.

**Comment by sthalik** [comment] 2015-10-24 10:00
My initial assumption that it's NaN could be wrong. Here's one more test build. It's FOR DEBUGGING only - will show a messagebox and crash on error.

DEBUG ONLY https://db.tt/NuN82lND

Other than that the bug should be in Accela but let's leave that after the build's feedback.

**Comment by Len62** [comment] 2015-10-24 11:50
Ran the debug version for 60 minutes. Locked-up once about ten minutes in, centering brought it back to life. No problems after that initial lock-up and it never did crash.

**Comment by sthalik** [comment] 2015-10-24 13:35
Then it's not what I originally thought. Try this build with a bit of Accela's logic ripped out - https://db.tt/VrgpjMzS

**Comment by sthalik** [comment] 2015-10-24 14:06
Here's a newer one with timer changes - https://db.tt/zjIM30tG

**Comment by Len62** [comment] 2015-10-24 14:47
I ran the first one, accela logic ripped out, ran for about 20 minutes w/o any issues. Just d/l the latest one and it might be little while before I can test it.

**Comment by Len62** [comment] 2015-10-24 22:11
Looking good! I just ran the last one for approximately 1 hr and 25 minutes w/o a single lock-up, and no other issues. I'll test some more later on tonight, or tomorrow. Seems rock-solid at this point.

**Comment by petsild** [comment] 2015-10-24 22:19
So far no freezing up, I'll be even more of a test today.

**Comment by samkatakouzinosracing** [comment] 2015-10-25 12:25
@sthalik https://db.tt/zjIM30tG is behaving very well with no minute nor extreme incidents. This is with multiple sessions lasting at least an hour each.

**Comment by petsild** [comment] 2015-10-25 16:07
Today I put 2x2h this same friend flight and holds no collision and freezing up the, good work.

**Comment by sthalik** [comment] 2015-10-25 17:01
@Len62 @petsild @samkatakouzinosracing thanks for testing. I've put up rc19p3. I'm leaving this issue open for now in case of last-minute problems.

**Comment by petsild** [comment] 2015-10-25 17:52
The P3 does not respond to the octopus?

**Comment by sthalik** [comment] 2015-10-25 18:13
Thanks, new binaries uploaded

**Comment by Len62** [comment] 2015-10-26 01:23
All good on this end.

**Comment by sthalik** [comment] 2015-10-26 05:36
@FlyingCircus- how is it?

**Comment by FlyingCircus-** [comment] 2015-10-26 06:11
Mmm... Hard to say. I never experienced such issues, but then again I haven't been playing sims the last 6 months so my tests with opentrack were always very brief. It seems everybody is happy now with your last fix, I will try the last version when I've a chance

**Comment by sthalik** [comment] 2015-10-26 06:20
Thanks for a prompt response.

**Comment by sthalik** [comment] 2015-10-27 07:49
Are we good everyone? Did you fly for several hours without the crap happening?

**Comment by Len62** [comment] 2015-10-27 09:24
I'm good here.

**Comment by sthalik** [comment] 2015-10-27 09:29
@petsild?

**Comment by petsild** [comment] 2015-10-27 16:31
Works well no crashes or lockups thank you for the correction.

**Comment by sthalik** [comment] 2015-10-28 02:24
Thanks! Closing.

**Closed by sthalik** 2015-10-28 02:24 UTC
Labels: blocker, todo
